### ISSUE TITLE
scoverageTest on a subproject that contains imports from a java source

### ISSUE THREAD

**Issue by terebesirobert** [scoverage/gradle-scoverage#56]
HI, 
I try to run gradle testScoverage. When it reaches a subproject that contains imports from a java source I have the following errors:

17:36:13.134 [ERROR] [system.err] 17:36:13.134 [ERROR] [org.gradle.api.internal.tasks.scala.ZincScalaCompiler] ... **not found: type** {class from the java source}

What can I do? I this something known?

**Comment by maiflai** [comment]
I thought this issue was resolved in the current release.

Please could you share the project (or at least provide a minimal example) so that I can investigate further?

Thanks,
Stu.

**Comment by terebesirobert** [comment]
Hey,
If I have the following example:

`class BEE[String] extends ArrayList[String] {
}`

If I run gradle testScoverage I get the following error:

fork has been deprecated and is scheduled to be removed in Gradle 3.0. The fork option for the scala compiler is deprecated, please see https://docs.gradle.org/current/userguide/scala_plugin.html.
/home/robert/projects/ul-bridge-modules-smart2/code/ulsmart-plugin/src/main/scala/com/ullink/smart/BEE.scala:5: type parameter String defined in class BEE shadows type String defined in object Predef. You may want to rename your type parameter, or possibly remove it.
class BEE[String] extends util.ArrayList[String] {
          ^
one error found
:code:ulsmart-plugin:compileScoverageScala FAILED

running it with gradle testScoverage --stacktrace

* What went wrong:
Execution failed for task ':code:ulsmart-plugin:compileScoverageScala'.
> Compilation failed

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test:compileScoverageScala'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)

**Comment by maiflai** [comment]
Hmm, that doesn't look like a scoverage issue - does 'gradle test' work please?

**Comment by maiflai** [comment]
Hi - is this issue still open please?

**Comment by terebesirobert** [comment]
Hi,
Sorry for the late answer. I still have the problem. Answering your previous question, yes, `gradle test` works fine.

The error that I have is the following:

:code:testsmart-plugin:compileScoverageJava UP-TO-DATE
:code:testsmart-plugin:compileScoverageScala
~/projects/test-bridge-modtestes-smart2/code/testsmart-plugin/src/main/scala/com/test/smart/BEE.scala:13: object SessionInterface is not a member of package com.test.testbridge2
import com.test.testbridge2.SessionInterface.{CONNECTED, DISCONNECTED, LOGGED, STOPPED}
                            ^
~/projects/test-bridge-modtestes-smart2/code/testsmart-plugin/src/main/scala/com/test/smart/BEE.scala:16: object testBridge is not a member of package com.test.testbridge2
import com.test.testbridge2.{testBridge, testMessage}
       ^
~/projects/test-bridge-modtestes-smart2/code/testsmart-plugin/src/main/scala/com/test/smart/BEE.scala:17: object NamingService is not a member of package com.test.testtools
import com.test.testtools.NamingService
       ^
Class com.test.testbridge2.ModtesteInterface not found - continuing with a stub.
Class com.test.testbridge2.AbstractSessionInterface not found - continuing with a stub.
Class com.test.testbridge2.testBridge not found - continuing with a stub.
Class com.test.testbridge2.enrichment.EnrichmentManager not found - continuing with a stub.
Class com.test.testtools.InitFile not found - continuing with a stub.
Class com.test.testtools.InitFile not found - continuing with a stub.
Class com.test.testtools.InitFile not found - continuing with a stub.
Class com.test.testtools.InitFile not found - continuing with a stub.
Class com.test.testtools.TraceFile not found - continuing with a stub.
Class com.test.testbridge2.enrichment.EnrichmentAttachment not found - continuing with a stub.
Class com.test.testbridge2.extendedactions.ExtendedAction not found - continuing with a stub.
Class com.test.testbridge2.extendedactions.ExtendedAction not found - continuing with a stub.
Class com.test.testbridge2.exceptions.BPluginOperationException not found - continuing with a stub.
Class com.test.testbridge2.exceptions.BPluginOperationException not found - continuing with a stub.
Class com.test.testbridge2.AbstractSessionInterface not found - continuing with a stub.
Class com.test.testbridge2.ModtesteInterface not found - continuing with a stub.
~/projects/test-bridge-modtestes-smart2/code/testsmart-plugin/src/main/scala/com/test/smart/BEE.scala:23: illegal inheritance;
 self-type com.test.smart.BEE does not conform to com.test.testbridge2.modtestes.common.Modteste's selftype com.test.testbridge2.modtestes.common.Modteste
class BEE extends Modteste {
                  ^
~/projects/test-bridge-modtestes-smart2/code/testsmart-plugin/src/main/scala/com/test/smart/BEE.scala:25: not found: value NamingService




At the end I have some unused imports error also.


Thanks

**Comment by maiflai** [comment]
Sorry, I'm a little confused by the various test directories - please could you confirm the location of the source for `com.test.testbridge2.SessionInterface`?

**Comment by terebesirobert** [comment]
Hi,
That's from an external java source.

**Comment by maiflai** [comment]
How is the dependency declared please?

**Comment by YusiZhang** [comment]
Did the OP solve the issue? I am facing a similar issue, where the scala source code has java code imported. The normal compileScala works fine but the compileScoverageScala task failed due to the java import not found.

**Comment by maiflai** [comment]
I think this regressed in the 3.0 release but has been fixed since then.

If you have an issue, please open a new one?

Thanks,
Stu.
